### ISSUE TITLE
cURL error: [35]

### ISSUE THREAD

**Issue by jsdecena** [sh0umik/Laravel5-PaypalIPN#4]
I am getting this error when I am trying to catch the post to this listener. Any idea why?

exception 'Exception' with message 'cURL error: [35] Cannot communicate securely with peer: no common encryption algorithm(s).' in /var/app/current/vendor/fahim/laravel5-paypal-ipn/src/PaypalIPNListener.php:120

line 20 is `throw new Exception("cURL error: [$errno] $errstr");`

**Comment by xyzale** [comment]
I am getting cURL error 35 with a different message. 

> cURL error: [35] error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'

I have a RapidSSL certificate installed.
I tried editing my webserver configuration adding the following lines:
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`
`ssl_prefer_server_ciphers on;`
`ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!$`

Then I tried passing the IPN trough http instead of https, but the error persists.

Any idea?

**Comment by dfanara** [comment]
This issue appears to be caused by PayPal's recent switch to a new certificate that supports SHA-256. I am looking into how to resolve it now as I am affected by the same issue.

**Comment by dfanara** [comment]
Pull request #3 appears to fix the issue.
